---
title: "digital_phenotype"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
```

# Load data
```{r}
output_data <- "results/"
ps_deseq <- readRDS("Filtered/ps_deseq_friedfilt.rds")
ps_css <- readRDS("Filtered/ps_css_friedfilt.rds")
```


```{r, pcoa_dig_phenotype, fig.height=5}
### Digital phenotype
correlation_test <- function(ps_A){
  sample_data(ps_A)$Mobile.Autism.Risk.Assessment.Score <- as.numeric(sample_data(ps_A)$Mobile.Autism.Risk.Assessment.Score)
  map <- ps_A@sam_data
  #Spearman test for taxa correlated with MARA with Deseq
  
  otus <- as.data.frame(otu_table(ps_A))
  otus <- t(otus)
  otus <- as.data.frame(otus)
  
  mapa <- map[which(map$phenotype == "A"),]
  otus$MARA <- mapa$Mobile.Autism.Risk.Assessment.Score
  form <- as.formula(paste("~", colnames(otus)[1], "+", "MARA"))
  tmp <- cor.test(formula = form, data = otus, method = "spearman",
           continuity = FALSE,
           conf.level = 0.95, exact = FALSE)
  
  speartesttab <- tibble(colnames(otus)[1], tmp$p.value)
  colnames(speartesttab) <- c("otu", "p_val")
  
  for (i in 2:(length(colnames(otus))-1)){
      otus$MARA <- mapa$Mobile.Autism.Risk.Assessment.Score
      form <- as.formula(paste("~", colnames(otus)[i], "+", "MARA"))
      tmp <- cor.test(formula = form, data = otus, method = "spearman",
           continuity = FALSE,
           conf.level = 0.95, exact = FALSE)
  
      tab <- tibble(colnames(otus)[i], tmp$p.value)
      colnames(tab) <- c("otu", "p_val")
      speartesttab <- rbind(speartesttab, tab)
  }
  
  spear_p.val <- p.adjust(speartesttab$p_val)
  spear_sig_asvs_p.val_des_all_MARA <- speartesttab$otu[spear_p.val < 0.05]
  return(spear_sig_asvs_p.val_des_all_MARA)
}

```

```{r}
#Spearman test for taxa correlated with MARA with CSS
ps_css <- subset_samples(ps_css, phenotype == "A")
ps_deseq <- subset_samples(ps_deseq, phenotype == "A")
spear_sig_asvs_p.val_des_all_MARA_css <- correlation_test(ps_css)
spear_sig_asvs_p.val_des_all_MARA_deseq <- correlation_test(ps_deseq)
dir.create(paste0(output_data, "digital_phenotype"))
saveRDS(spear_sig_asvs_p.val_des_all_MARA_css, paste0(output_data, "digital_phenotype/spearman_asv_mara_css.rds"))
saveRDS(spear_sig_asvs_p.val_des_all_MARA_deseq, paste0(output_data, "digital_phenotype/spearman_asv_mara_deseq.rds"))
```

```{r deseq_by_timepoint}

#Timepoint 1

P1_des <- prune_samples(rownames(sample_data(ps_deseq))[sample_data(ps_deseq)$Within.study.sampling.date == "Timepoint 1"], ps_deseq)
spear_sig_asvs_p.val_des_time1_MARA_deseq <- correlation_test(P1_des)


#Timepoint 2

P2_des <- prune_samples(rownames(sample_data(ps_deseq))[sample_data(ps_deseq)$Within.study.sampling.date == "Timepoint 2"], ps_deseq)
spear_sig_asvs_p.val_des_time2_MARA_deseq <- correlation_test(P2_des)


#Timepoint 3

P3_des<-prune_samples(rownames(sample_data(ps_deseq))[sample_data(ps_deseq)$Within.study.sampling.date == "Timepoint 3"], ps_deseq)
spear_sig_asvs_p.val_des_time3_MARA_deseq <- correlation_test(P3_des)
```

```{r css_by_timepoint}
#Timepoint 1

P1_des <- prune_samples(rownames(sample_data(ps_css))[sample_data(ps_css)$Within.study.sampling.date == "Timepoint 1"], ps_css)
spear_sig_asvs_p.val_des_time1_MARA_css <- correlation_test(P1_des)


#Timepoint 2

P2_des <- prune_samples(rownames(sample_data(ps_css))[sample_data(ps_css)$Within.study.sampling.date == "Timepoint 2"], ps_css)
spear_sig_asvs_p.val_des_time2_MARA_css <- correlation_test(P2_des)


#Timepoint 3

P3_des<-prune_samples(rownames(sample_data(ps_css))[sample_data(ps_css)$Within.study.sampling.date == "Timepoint 3"], ps_css)
spear_sig_asvs_p.val_des_time3_MARA_css <- correlation_test(P3_des)
```


```{r plot_wo_na}
# function to plot PCoA without NA points
wo_na_pcoa <- function(ps, pvar, ord_res){
  # ord_res: ordinated object
  
  keepid=!is.na(get_variable(ps, pvar)) &
    get_variable(ps, pvar)!='NA' &
    get_variable(ps, pvar)!=''
  tmp_ps <- prune_samples(keepid, ps)
  
  # get subset counts and metadata together
  DF <- cbind(ord_res$vectors[row.names(sample_data(tmp_ps)), 1:2], sample_data(tmp_ps)[, pvar])
  setnames(DF, pvar, 'testvar')
  
  # get eigenvalues
  eig=(ord_res$values$Eigenvalues/sum(ord_res$values$Eigenvalues))[1:2]*100
  
  p <- ggplot(data=DF, aes(x=Axis.1, y=Axis.2, colour=testvar))+
    geom_point(size=2)+
    ggtitle(pvar)+
    xlab(paste0('Axis.1 [', format(eig[1], digits=3), '%]'))+
    ylab(paste0('Axis.2 [', format(eig[2], digits=3), '%]'))+
    theme_minimal()+
    theme(legend.title=element_blank(), legend.position="bottom")
    
  print(p)
}
ord <- ordinate(ps_css, method = "PCoA", distance = "bray")
wo_na_pcoa(ps_css, 'Mobile.Autism.Risk.Assessment.Score', ord)
```

