---
title: "Random_Forest"
author: "Austin Martin"
date: "8/25/2020"
output: html_document
---

## Load libraries
```{r cache=FALSE, include=TRUE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE, cache=FALSE, fig.path=paste0('./Figures_', Sys.Date(), '/')) 
# utility
library(shiny)
library(tibble)
library(data.table)
library(devtools)
library(knitr)
library(tidyr)
library(reshape2)
library(dplyr)
# visualization
library(ggplot2)
library(pander)
library(DT)
library(gridExtra)
library(adegraphics)
library(stats)
library(smatr)
library(caret)
library(randomForest)
library(ROCR)
library(phyloseq)
library(exactRankTests)
library(nlme)
library(compositions)
```

### Load ASVs

```{r load}
fullsigtab_esv<-read.csv(file = "EnrichmentASV_Table_8_26_2020.csv")
fullsigtab_esv$rn <- as.character(fullsigtab_esv$ASV)

full_sigtab_esv_confoundfiltered <- read.csv(file = "Des_Metag_taxapcoa_sig_asvs_w_confounding_var_asvs_filtered_out.csv")
rownames(full_sigtab_esv_confoundfiltered) <- full_sigtab_esv_confoundfiltered$x 

ps_DeSeq_norm_pass_min_postDD_sup003 <- readRDS(file = "Filtered/ps_deseq_friedfilt.rds")

```
### Random Forest

```{r randomforest}

#Random Forest main function
rand_forest <- function(pred_sequences, ps){ 

  
  ps <-prune_taxa(pred_sequences, ps )
  phen <- sample_data(ps)$phenotype
  family <- unique(sample_data(ps)$Family.group.ID)
  fam_id <- sample_data(ps)$Family.group.ID
  
  data<-t(otu_table(ps))
  data <- data.frame(phen, data, fam_id)

  set.seed(103)
  folds_by_family<-groupKFold(fam_id, 10)
  
  validate <- data[-folds_by_family[[1]],]
  training <- data[folds_by_family[[1]],]


  validate$fam_id <- NULL
  training$fam_id <- NULL
  
  set.seed(1)
  control <- trainControl(method='repeatedcv', 
                        number=3, 
                        repeats=3)

  tunegrid <- expand.grid(.mtry=c(3:20)) #mtry is the depth of each decision tree
  rf <- train(phen ~., 
            data= training, 
            method='rf', 
            metric='Accuracy', 
            tuneGrid=tunegrid, 
            trControl=control)


  mtry_best = as.numeric(rf$bestTune)

  set.seed(1)
  AR.classify <- randomForest(phen~., data = training, ntree = 128, mtry = mtry_best, importance = TRUE)
  rf<-AR.classify
  OOB.votes <- predict(rf,validate[,-1],type="prob");
  OOBpred_votes <- OOB.votes

  pred_votes <- OOBpred_votes[,2]


  for(i in 2:10){
  
  
    validate <- data[-folds_by_family[[i]],]
    training <- data[folds_by_family[[i]],]

    validate$fam_id <- NULL
    training$fam_id <- NULL
  
  
    set.seed(1)
    control <- trainControl(method='repeatedcv', 
                        number=3, 
                        repeats=3)

    tunegrid <- expand.grid(.mtry=c(3:20)) #mtry is the depth of each decision tree
    rf <- train(phen ~., 
            data= training, 
            method='rf', 
            metric='Accuracy', 
            tuneGrid=tunegrid, 
            trControl=control)
  
    mtry_best = as.numeric(rf$bestTune)
  
    set.seed(1)
    AR.classify <- randomForest(phen~., data = training, ntree = 128, mty = mtry_best, importance = TRUE)
    rf<-AR.classify
    OOB.votes <- predict (rf,validate[,-1],type="prob");
  
    OOB.votes
    pred_votes<-append(pred_votes, OOB.votes[,2])
  
  
  }
  a<-tibble(names(pred_votes), pred_votes)
  b <- a[order(a$`names(pred_votes)`), ]
  data<- data[order(rownames(data)),]


  pred.obj <- prediction(b$pred_votes,data$phen);
  perf_AUC=performance(pred.obj,"auc") #Calculate the AUC value
  AUCagp1=perf_AUC@y.values[[1]]
  AUCagp1
  RP.perf <- performance(pred.obj, "prec","rec");
  ROC.perfAGP <- performance(pred.obj, "tpr","fpr");
  outputlist <-list()
  outputlist[1] <- AUCagp1
  outputlist[2] <- ROC.perfAGP
  return(outputlist)

}

#For 33 (set of asvs with confounds filtered out)
ROC.perf_33 <-rand_forest(pred_sequences = rownames(full_sigtab_esv_confoundfiltered), ps = ps_DeSeq_norm_pass_min_postDD_sup003)

#For 69 (unfiltered results)
ROC.perf_69 <-rand_forest(fullsigtab_esv$rn, ps_DeSeq_norm_pass_min_postDD_sup003)

#For 11 (ASVs from the 33 who are consistantly enriched/depleted over timepoints)
#ROC.perf_11_all <-rand_forest(pred_sequences = full_sigtab_esv_confoundfiltered_consist$ASV, ps = ps_DeSeq_norm_pass_min_postDD_sup003)


#Combine AUCs
AUC_all <- c(ROC.perf_33[1], ROC.perf_69[1])#, ROC.perf_11_all[1])

#Plot
{plot(ROC.perf_33[[2]], main = "10-Cross Validation for ASD Classification", col = rainbow(8)[1])
plot(ROC.perf_69[[2]], main = "10-cross validation", col = rainbow(8)[2], add = TRUE)
#plot(ROC.perf_11_all[[2]], main = "10-cross validation", col = rainbow(8)[3], add = TRUE)
lines(c(0,1), c(0,1), col = "black")
legend(title = "AUC value", .81, .33, legend=round(as.numeric(AUC_all), digits = 4),
       col=colors,cex=1.0)

predictors_name <- c("59 Diff. Abundant ASVs", "98 Diff. Abundant ASVs") #, "Selected 11 ASVs")
legend(title = "Predictors",.375, .33, legend=predictors_name,
       col=c(rainbow(8)[c(1,2,3,5,7,6,8)], hcl.colors(1, palette = "viridis")),cex=1.0, lty=1:7)
}




#Per timepoints

P1_des<-prune_samples(rownames(sample_data(ps_DeSeq_norm_pass_min_postDD_sup003))[sample_data(ps_DeSeq_norm_pass_min_postDD_sup003)$Within.study.sampling.date == "Timepoint 1"], ps_DeSeq_norm_pass_min_postDD_sup003)
P2_des<-prune_samples(rownames(sample_data(ps_DeSeq_norm_pass_min_postDD_sup003))[sample_data(ps_DeSeq_norm_pass_min_postDD_sup003)$Within.study.sampling.date == "Timepoint 2"], ps_DeSeq_norm_pass_min_postDD_sup003)
P3_des<-prune_samples(rownames(sample_data(ps_DeSeq_norm_pass_min_postDD_sup003))[sample_data(ps_DeSeq_norm_pass_min_postDD_sup003)$Within.study.sampling.date == "Timepoint 3"], ps_DeSeq_norm_pass_min_postDD_sup003)


ROC.perf_33_P1 <-rand_forest(pred_sequences = rownames(full_sigtab_esv_confoundfiltered), ps = P1_des)
ROC.perf_33_P2 <-rand_forest(pred_sequences = rownames(full_sigtab_esv_confoundfiltered), ps = P2_des)
ROC.perf_33_P3 <-rand_forest(pred_sequences = rownames(full_sigtab_esv_confoundfiltered), ps = P3_des)
AUC_all <- c(ROC.perf_33_P1[1], ROC.perf_33_P2[1], ROC.perf_33_P3[1])


{plot(ROC.perf_33_P1[[2]], main = "10-cross validation for 59 Sequences by Timepoint", col = rainbow(8)[1])
plot(ROC.perf_33_P2[[2]], main = "10-cross validation", col = rainbow(8)[2], add = TRUE)
plot(ROC.perf_33_P3[[2]], main = "10-cross validation", col = rainbow(8)[3], add = TRUE)
lines(c(0,1), c(0,1), col = "black")
legend(title = "AUC value", .850, .33, legend=round(as.numeric(AUC_all), digits = 4),
       col=colors,cex=1.0)

predictors_name <- c("59 Diff. Abundant ASVs P1", "59 Diff. Abundant ASVs P2","59 Diff. Abundant ASVs P3")
legend(title = "Predictors",.375, .33, legend=predictors_name,
       col=c(rainbow(8)[c(1,2,3,5,7,6,8)], hcl.colors(1, palette = "viridis")),cex=1.0, lty=1:7)
}


ROC.perf_69_P1 <-rand_forest(pred_sequences = fullsigtab_esv$rn, ps = P1_des)
ROC.perf_69_P2 <-rand_forest(pred_sequences = fullsigtab_esv$rn, ps = P2_des)
ROC.perf_69_P3 <-rand_forest(pred_sequences = fullsigtab_esv$rn, ps = P3_des)
AUC_all <- c(ROC.perf_69_P1[1], ROC.perf_69_P2[1], ROC.perf_69_P3[1])


{plot(ROC.perf_69_P1[[2]], main = "10-cross validation for 98 Sequences by Timepoint", col = rainbow(8)[1])
plot(ROC.perf_69_P2[[2]], main = "10-cross validation", col = rainbow(8)[2], add = TRUE)
plot(ROC.perf_69_P3[[2]], main = "10-cross validation", col = rainbow(8)[3], add = TRUE)
lines(c(0,1), c(0,1), col = "black")
legend(title = "AUC value", .850, .33, legend=round(as.numeric(AUC_all), digits = 4),
       col=colors,cex=1.0)

predictors_name <- c("98 Diff. Abundant ASVs P1", "98 Diff. Abundant ASVs P2","98 Diff. Abundant ASVs P3")
legend(title = "Predictors",.375, .33, legend=predictors_name,
       col=c(rainbow(8)[c(1,2,3,5,7,6,8)], hcl.colors(1, palette = "viridis")),cex=1.0, lty=1:7)
}





```

```{r look}

ps<-readRDS(file = "Normalized/ps_tss_pass_min_postDD_min0.03.rds")
table_of_all<-cbind(fullsigtab_esv, tax_table(ps)[rownames(tax_table(ps)) %in% fullsigtab_esv$rn,])

table_of_38<-table_of_all[which(rownames(table_of_all) %in% rownames(full_sigtab_esv_confoundfiltered)),]

#none
table_of_38$deseq_timeseries_adjp


### functions to plot (WORKS ONLY IN R3.6.2)
make_vis_plots_print <- function(ps_norm, grouping, tax, plot_type=c('box', 'bar'), plot_title){
  # ps should be a normalized (DESeq or CSS) phyloseq object
  # grouping should match the column name in the sample_data
  # tax is a taxonomical bin id (ASV) in the counts table to plot
  
  # subset phyloseq object to select ASV of interest
  ps_filt=prune_taxa(taxa_names(ps_norm) %in% tax, ps_norm)
  
  # get normalized counts
  plot_table<-data.table(otu_table(ps_filt), keep.rownames=TRUE)[rn %in% tax]
  # add very small value, min/100000 to 0
  plot_table <- melt(plot_table, id.vars='rn')
  plot_table$value <- plot_table$value+min(plot_table[value!=0]$value)/100000
  
  # add metadata
  groupDT=data.table(data.frame(sample_data(ps_filt)[, c(grouping, 'Within.study.sampling.date')]), keep.rownames=TRUE)
  setnames(groupDT, 'rn', 'variable')
  plot_table <- merge(plot_table, groupDT, by='variable', all.x=TRUE)
  
  # change variable to general name
  setnames(plot_table, grouping, 'Group')

  # boxplot
  if(plot_type=='box'){
    ggplot(data=plot_table, aes(x=Within.study.sampling.date, y = value, fill=Group)) + 
      geom_boxplot(outlier.color=NA) +
      geom_jitter(position=position_jitterdodge(0.2), cex=1.5, color="gray44") + 
      labs(title =deparse(substitute(ps_norm)), x='', y ='Proportional counts, log scale') + 
      scale_y_log10() + 
      scale_fill_manual(values=sgColorPalette)+
      theme_minimal() + facet_wrap(~rn, scales='free', ncol=3)+
      theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
  } else if (plot_type=='bar'){
    plot_table2 <- plot_table[, list(mean_ct=mean(value), sem=sd(value)/sqrt(.N)), by=c('Group', 'Within.study.sampling.date', 'rn')]
    ggplot(data=plot_table2, aes(x=Within.study.sampling.date, y =mean_ct, fill=Group)) + 
      geom_bar(stat='identity', position=position_dodge()) +
      geom_errorbar(aes(ymin=mean_ct-sem, ymax=mean_ct+sem), width=0.2, position=position_dodge(0.9))+ 
      labs(title =plot_title, x='', y ='Proportional counts, 0 to 1 scale') + 
      #scale_y_log10() + 
      scale_fill_manual(values=sgColorPalette)+
      theme_minimal() + facet_wrap(~rn, scales='free', ncol=3)+
      theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
  }
}

#14
across_all<-table_of_38[is.na(table_of_38$mtgseq_timeseries_adjp) == FALSE,]
across_all$Genus

across_all$Genusp <- gsub("g__", "", across_all$Genus)

across_all$Classp <- gsub("c__", "", across_all$Class)


# plotting consistently enriched/depleted ones 
make_vis_plots_print(ps, 'phenotype', across_all$rn[3], 'bar', across_all$Genusp[3])
```
